#端口配置
server:
  port: 8888
  servlet:
    context-path: /springboot

#数据库
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/testdb?characterEncoding=utf8&useSSL=false
    username: test
    password: test

    #AOP配置
    aop:
      auto: true

#mybatis的扫描的xml
  mybatis:
    mapper-locations: classpath:mapper/*.xml

#日志显示SQL
logging.level:
  com.springboot.demo.mapper: debug